version: "3"
services:
  postgres:
    container_name: music-platform-postgres
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: music-platform-api
    build:
      context: ./server
      dockerfile: Dockerfile # on move to prod, update this
    volumes:
      - /app/node_modules
      - ./server/src:/app/src
      - ./server/public:/app/public
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
  web_app:
    container_name: music-platform-web_app
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env.local
    volumes:
      - /app/node_modules
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/.env:/app/.env
    ports:
      - "3000:3000"
  pgadmin-compose:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@megacorp.com"
      PGADMIN_DEFAULT_PASSWORD: "s3kr1t_p455w0rd"
    ports:
      - "16543:80"
    depends_on:
      - postgres
