const tracks = [
  {
    title: "$orries",
    artist: "Peachy!",
    album: " Shiloh",
    image: `/static/images/$orries_Cover (front)_e.jpg`,
    audio: `/static/audio/$orries.mp3`,
  },
  {
    title: "[oops]",
    artist: "potsu",
    album: "[oops]",
    image: `http://localhost:5000/images/1.jpg`,
    audio: `http://localhost:5000/track/1`,
  },
  {
    title: "5:32pm",
    artist: "The Deli",
    album: "Vibes 2",
    image: `/static/images/5 32pm_Cover (front)_e.jpg`,
    audio: `/static/audio/5 32pm.mp3`,
  },
  {
    title: "88 Keys",
    artist: "Oatmello",
    album: "Snapshots",
    image: `/static/images/88 Keys_Cover (front)_e.jpg`,
    audio: `/static/audio/88 Keys.mp3`,
  },
  {
    title: "Affection",
    artist: "Jinsang",
    album: "Life",
    image: `/static/images/Affection_Cover (front)_e.jpg `,
    audio: `/static/audio/Affection.mp3`,
  },
  {
    title: "Again",
    artist: "Wun Two",
    album: "Penthouse",
    image: `/static/images/Again_Cover (front)_e.jpg`,
    audio: `/static/audio/Again.mp3`,
  },
  {
    title: "Alone and Lonely",
    artist: "prxz",
    album: " Shiloh Dynasty",
    image: `/static/images/Alone and Lonely_Cover (front)_e.jpg`,
    audio: `/static/audio/Alone and Lonely.mp3`,
  },
  {
    title: "Baby You're Worth It",
    artist: "Kina",
    album: "Baby You're Worth It",
    image: `/static/images/Baby You're Worth It_Cover (front)_e.jpg`,
    audio: `/static/audio/Baby You're Worth It.mp3`,
  },
  {
    title: "Backpack City",
    artist: "Flovry",
    album: " tender spring",
    image: `/static/images/Beauty_Cover (front)_e.jpg`,
    audio: `/static/audio/Backpack City.mp3`,
  },
  {
    title: "Beauty",
    artist: "eyeroze",
    album: "Heartless",
    image: `/static/images/Beauty_Cover (front)_e.jpg`,
    audio: `/static/audio/Beauty.mp3`,
  },
  {
    title: "Better Than He Can",
    artist: "Jennifer Flores",
    album: " Shiloh Dynasty",
    image: `/static/images/Better Than He Can_Cover (front)_e.jpg`,
    audio: `/static/audio/Better Than He Can.mp3`,
  },
  {
    title: "Break My Heart Again",
    artist: "90degrees",
    album: "Break My Heart Again",
    image: `/static/images/Break My Heart Again_Cover (front)_e.jpg`,
    audio: `/static/audio/Break My Heart Again.mp3`,
  },
  {
    title: "Brightness",
    artist: "eyeroze",
    album: "Heartless",
    image: `/static/images/Brightness_Cover (front)_e.jpg`,
    audio: `/static/audio/Brightness.mp3`,
  },
  {
    title: "Call me",
    artist: "90sFlav",
    album: "Collection",
    image: `/static/images/Call me_Cover (front)_e.jpg`,
    audio: `/static/audio/Call me.mp3`,
  },
  {
    title: "Can We Kiss Forever?",
    artist: "Kina",
    album: " Adriana Proenza",
    image: `/static/images/Can We Kiss Forever _Cover (front)_e.jpg`,
    audio: `/static/audio/Can We Kiss Forever .mp3`,
  },
];

export default tracks;
